### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [deplug/deplug#2]
Hi @h2so5 , 

I am a graphic designer and i designed a logo for deplug. I used the graphics icon and the d letter. Please tell me what you think about this logolar. If you like it, i can send a pr.

I will wait for feedback.

![deplug](https://user-images.githubusercontent.com/36298335/43135511-588f6888-8f4e-11e8-8b74-c0f0ebd9625a.jpg)

**Comment by h2so5** [comment]
Hello, @reallinfo .
Thank you so much for your logo!

I'm afraid to say that a logo contribution is not acceptable because I want to design my projects by myself (I'm also a graphic designer). However, I'm very glad about your proposal. It's the first time someone designs my project logo. 🎉

**My thoughts about your logo:**
Pros: So cute typography! The d-letter and icon are beautifully balanced.
Cons: Theme color is a bit muddy and uninteresting. Don't afraid using more vivid and sharp tone.

**Comment by reallinfo** [comment]
Thank you for your comment and I wish success in your projects!
